### ISSUE TITLE
Facing issue with deploying 

### ISSUE THREAD

**Issue by ajaydesai** [dlo/in_app_purchase_receipt_verifier#1]
getting below error 

```
Build app  Hide build log
There was an issue building your app. This can mean your app.json's project is not a valid Heroku application. Please ensure your app is deployable to Heroku and try again.

-----> $ python manage.py collectstatic --noinput
       Traceback (most recent call last):
         File "/tmp/build_b5a98b2167870f23906d74d7e0566400/lionheart-in_app_purchase_receipt_verifier-483e1be/settings.py", line 220, in <module>
           environment = os.environ['APP_ENVIRONMENT']
         File "/app/.heroku/python/lib/python3.6/os.py", line 669, in __getitem__
           raise KeyError(key) from None
       KeyError: 'APP_ENVIRONMENT'
       During handling of the above exception, another exception occurred:
       Traceback (most recent call last):
         File "manage.py", line 20, in <module>
           execute_from_command_line(sys.argv)
         File "/app/.heroku/python/lib/python3.6/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
           utility.execute()
         File "/app/.heroku/python/lib/python3.6/site-packages/django/core/management/__init__.py", line 308, in execute
           settings.INSTALLED_APPS
         File "/app/.heroku/python/lib/python3.6/site-packages/django/conf/__init__.py", line 56, in __getattr__
           self._setup(name)
         File "/app/.heroku/python/lib/python3.6/site-packages/django/conf/__init__.py", line 41, in _setup
           self._wrapped = Settings(settings_module)
         File "/app/.heroku/python/lib/python3.6/site-packages/django/conf/__init__.py", line 110, in __init__
           mod = importlib.import_module(self.SETTINGS_MODULE)
         File "/app/.heroku/python/lib/python3.6/importlib/__init__.py", line 126, in import_module
           return _bootstrap._gcd_import(name[level:], package, level)
         File "<frozen importlib._bootstrap>", line 978, in _gcd_import
         File "<frozen importlib._bootstrap>", line 961, in _find_and_load
         File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
         File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
         File "<frozen importlib._bootstrap_external>", line 678, in exec_module
         File "<frozen importlib._bootstrap>", line 205, in _call_with_frames_removed
         File "/tmp/build_b5a98b2167870f23906d74d7e0566400/lionheart-in_app_purchase_receipt_verifier-483e1be/settings.py", line 222, in <module>
           raise Exception("""Please set your app environment (APP_ENVIRONMENT).""")
       Exception: Please set your app environment (APP_ENVIRONMENT).
 !     Error while running '$ python manage.py collectstatic --noinput'.
       See traceback above for details.
       You may need to update application code to resolve this error.
       Or, you can disable collectstatic for this application:
          $ heroku config:set DISABLE_COLLECTSTATIC=1
       https://devcenter.heroku.com/articles/django-assets
 !     Push rejected, failed to compile Python app.
 !     Push failed
```

**Comment by dlo** [comment]
Thanks @ajaydesai, looking into it. Fix should be on master soon.

**Comment by dlo** [comment]
@ajaydesai This should be working now! Please close if you have no other issues. 👍

**Comment by ajaydesai** [comment]
@dlo Thanks for quick fix , I will check that out and update you soon, One question 
what I need to pass in field called 
"BASE64_ENCODED_SIGNING_KEY"
Optional, but required if you'd like to verify payloads end-to-end. See README for information on what to provide for this value.

Do I need to copy paste the publicKeyString here from payload file ?

**Comment by ajaydesai** [comment]
issue fixed, thanks

**Comment by dlo** [comment]
@ajaydesai Did the instructions in the README clear that value up for you? To clarify, the string after "private key" is what you want to paste into that field.
