### ISSUE TITLE
Update needed for the newest Heroku-22 stack

### ISSUE THREAD

**Issue by Mariusz558** [dlo/in_app_purchase_receipt_verifier#9]
Hi @dlo @rloewenherz 

the newest Heroku stack, which is Heroku-22, requires python-3.10.7. 

Could you please update the settings?

Cheers
Mariusz

**Comment by Mariusz558** [comment]
I've updated Python to 3.10.7 and now I cannot deploy due to the following error:

-----> $ python manage.py collectstatic --noinput
       Traceback (most recent call last):
         File "/tmp/build_0207dfb0/manage.py", line 8, in <module>
           from django.core.management import execute_from_command_line
         File "/app/.heroku/python/lib/python3.10/site-packages/django/core/management/__init__.py", line 13, in <module>
           from django.core.management.base import (
         File "/app/.heroku/python/lib/python3.10/site-packages/django/core/management/base.py", line 17, in <module>
           from django.db.migrations.exceptions import MigrationSchemaMissing
         File "/app/.heroku/python/lib/python3.10/site-packages/django/db/migrations/__init__.py", line 2, in <module>
           from .operations import *  # NOQA
         File "/app/.heroku/python/lib/python3.10/site-packages/django/db/migrations/operations/__init__.py", line 1, in <module>
           from .fields import AddField, AlterField, RemoveField, RenameField
         File "/app/.heroku/python/lib/python3.10/site-packages/django/db/migrations/operations/fields.py", line 4, in <module>
           from django.db.models.fields import NOT_PROVIDED
         File "/app/.heroku/python/lib/python3.10/site-packages/django/db/models/__init__.py", line 5, in <module>
           from django.db.models.deletion import (
         File "/app/.heroku/python/lib/python3.10/site-packages/django/db/models/deletion.py", line 5, in <module>
           from django.db.models import signals, sql
         File "/app/.heroku/python/lib/python3.10/site-packages/django/db/models/sql/__init__.py", line 2, in <module>
           from django.db.models.sql.query import *  # NOQA
         File "/app/.heroku/python/lib/python3.10/site-packages/django/db/models/sql/query.py", line 11, in <module>
           from collections import Counter, Iterator, Mapping, OrderedDict
       ImportError: cannot import name 'Iterator' from 'collections' (/app/.heroku/python/lib/python3.10/collections/__init__.py)
 !     Error while running '$ python manage.py collectstatic --noinput'.
       See traceback above for details.
       You may need to update application code to resolve this error.
       Or, you can disable collectstatic for this application:
          $ heroku config:set DISABLE_COLLECTSTATIC=1
       https://devcenter.heroku.com/articles/django-assets
 !     Push rejected, failed to compile Python app.
 !     Push failed

@dlo  Any idea how to solve this?
